//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppWebServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cache
    {
        public string data { get; set; }
        public string md5 { get; set; }
        public string name { get; set; }
        public Nullable<bool> expired { get; set; }
        public Nullable<System.DateTime> expiredDateTime { get; set; }
    }
}
