//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppWebServer.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class EventPage
    {
        public EventPage()
        {
            this.SignForm = new HashSet<SignForm>();
            this.UserSlv = new HashSet<UserSlv>();
            this.Slvs = new HashSet<Slvs>();
        }
    
        public int eid { get; set; }
        public string url { get; set; }
        public string name { get; set; }
        public string html { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}")]
        public Nullable<System.DateTime> dateStart { get ; set; }
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}")]
        public Nullable<System.DateTime> dateEnd { get; set; }
        public Nullable<int> slvLimit { get; set; }
        public Nullable<int> toGoldNum { get; set; }
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd HH:mm}")]
        public Nullable<System.DateTime> postDate { get; set; }
        public string evenType { get; set; }
    
        public virtual ICollection<SignForm> SignForm { get; set; }
        public virtual ICollection<UserSlv> UserSlv { get; set; }
        public virtual ICollection<Slvs> Slvs { get; set; }
    }
}
