//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppWebServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gold
    {
        public int goldId { get; set; }
        public string goldname { get; set; }
        public string html { get; set; }
        public string potos { get; set; }
        public Nullable<int> goldnum { get; set; }
        public byte[] qrcode { get; set; }
        public Nullable<bool> isEnable { get; set; }
        public Nullable<int> ownerUserId { get; set; }
        public Nullable<int> totalUsetimes { get; set; }
        public Nullable<int> userUsetimes { get; set; }
        public Nullable<System.DateTime> lastEditDateTime { get; set; }
    
        public virtual User User { get; set; }
    }
}
