//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppWebServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class store
    {
        public int storeId { get; set; }
        public string storeName { get; set; }
        public string sotrePhone { get; set; }
        public string sotreAddr { get; set; }
        public string sotreWeb { get; set; }
        public string sotreWeb2 { get; set; }
        public string potos { get; set; }
        public string products { get; set; }
        public Nullable<bool> isEnable { get; set; }
        public Nullable<int> stId { get; set; }
        public Nullable<int> ownerUser { get; set; }
        public string html { get; set; }
        public string stroeMapLocation { get; set; }
    
        public virtual StoreType StoreType { get; set; }
        public virtual User User { get; set; }
    }
}
