//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppWebServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserSlv
    {
        public int eId { get; set; }
        public int userId { get; set; }
        public string name { get; set; }
        public Nullable<int> currNum { get; set; }
        public Nullable<int> accNum { get; set; }
        public Nullable<System.DateTime> dateStart { get; set; }
        public Nullable<System.DateTime> dateEnd { get; set; }
    
        public virtual EventPage EventPage { get; set; }
        public virtual User User { get; set; }
    }
}
