//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppWebServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.SignRecords = new HashSet<SignRecords>();
            this.UserSlv = new HashSet<UserSlv>();
            this.store = new HashSet<store>();
            this.UserCoinReord = new HashSet<UserCoinReord>();
        }
    
        public int userId { get; set; }
        public string userName { get; set; }
        public string phone { get; set; }
        public string oAuth { get; set; }
        public Nullable<int> powerGroup { get; set; }
        public Nullable<bool> isEanble { get; set; }
        public string password { get; set; }
        public string loginName { get; set; }
        public string deviceId { get; set; }
        public string token { get; set; }
        public Nullable<System.DateTime> tokendate { get; set; }
        public Nullable<int> goldnum { get; set; }
    
        public virtual ICollection<SignRecords> SignRecords { get; set; }
        public virtual ICollection<UserSlv> UserSlv { get; set; }
        public virtual ICollection<store> store { get; set; }
        public virtual ICollection<UserCoinReord> UserCoinReord { get; set; }
    }
}
